---
kind: pipeline
type: docker
name: docker-build-and-push

trigger:
  branch:
    - master

image_pull_secrets:
  - DOCKER_AUTH

steps:
  - name: build site
    # https://hub.docker.com/r/library/docker
    image: docker.struchkov.dev/quartz:latest
    commands:
      - cp -r ./* /usr/src/app/content
      - cp ./.quartz/quartz.config.ts /usr/src/app/
      - cp ./.quartz/quartz.layout.ts /usr/src/app/
      - cd /usr/src/app/
      - npx quartz build
      - mv /usr/src/app/public /drone/src
  - name: publish to server
    image: private.docker.struchkov.dev/mkdocs:latest
    environment:
      SSH_DEPLOY_KEY:
        from_secret: SSH_DEPLOY_KEY
      SSH_DEPLOY_HOST:
        from_secret: SSH_DEPLOY_HOST
      SSH_DEPLOY_PORT:
        from_secret: SSH_DEPLOY_PORT
      SSH_DEPLOY_PATH:
        from_secret: SSH_DEPLOY_PATH
      SSH_DEPLOY_USER:
        from_secret: SSH_DEPLOY_USER
    commands:
      - eval $(ssh-agent -s)
      - mkdir -p ~/.ssh
      - echo "$SSH_DEPLOY_KEY" >> ~/.ssh/id_rsa
      - chmod 700 ~/.ssh
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -p $SSH_DEPLOY_PORT $SSH_DEPLOY_HOST >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      - ls -la
      - ssh -p $SSH_DEPLOY_PORT $SSH_DEPLOY_USER@$SSH_DEPLOY_HOST "rm -rf $SSH_DEPLOY_PATH/*"
      - scp -r -P $SSH_DEPLOY_PORT ./public/* $SSH_DEPLOY_USER@$SSH_DEPLOY_HOST:$SSH_DEPLOY_PATH


# drone sign --save upagge/digital-garden
---
kind: signature
hmac: 9bdad34d737e99f66f9a6fdf42f3b212d3c4bd40fdd0413624925903b9481e1c

...
